name: Publish package
on:
    push:
        branches: master
    workflow_dispatch:
permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

            - uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

            - uses: actions/cache@v3
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - run: yarn install
            - run: yarn test:coverage

            - run: YARN_VERSION_GIT_TAG=''
            - run: npm version minor --no-git-tag-version

            - run: yarn build
            - run: cd ./.bin && npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Commit files
              run: |
                  git config --local user.email "$GITHUB_ACTOR+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "$GITHUB_ACTOR"
                  git commit --allow-empty -m "Version Bump"
                  git push origin master

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
